POST http://localhost:3001/api/blogs
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbW15QHNoZWxieS5maSIsImlkIjoxLCJpYXQiOjE2NzA2NzM4MTJ9.ONdxXoBgxlfTBWdGsr1JP6CwHLOP0XTd5WsPAWO1TPI

{
  "title": "Gangster blog 0",
  "author": "thomas shelby",
  "url": "https://peakyblinders.fi"
}
